FROM ubuntu:14.04

RUN apt-get update -y && apt-get upgrade -y
RUN apt-get install -y git wget

#install necessary packages
RUN git clone https://github.com/RECONet/RECO.git
#RUN cd RECO/ && git checkout 2c39c8e928b11bf8dfb191295c2691ce8d708fc8
RUN cd RECO/SCRIPTS/ && yes | ./build_spgw -f -i
RUN cd RECO/SCRIPTS/ && echo "\n\n\n\n\n" | ./build_mme -f -i
RUN /RECO/SCRIPTS/build_hss -i -F

#copy mme config
RUN cd RECO/ETC && cp spgw.conf /usr/local/etc/oai && chmod 777 /usr/local/etc/oai/spgw.conf

#build spgw
RUN cd RECO/SCRIPTS && ./build_spgw -c

#install necessary package 
RUN apt-get install -y iptables

#config spgw
RUN sed -i 's/PGW_MASQUERADE_SGI                    = "no";/PGW_MASQUERADE_SGI                    = "yes";/g' /usr/local/etc/oai/spgw.conf
RUN sed -i 's/UE_TCP_MSS_CLAMPING                   = "no";/UE_TCP_MSS_CLAMPING                   = "yes";/g' /usr/local/etc/oai/spgw.conf
RUN sed -i 's/PGW_INTERFACE_NAME_FOR_SGI            = "eth3";/PGW_INTERFACE_NAME_FOR_SGI            = "eth0";/g' /usr/local/etc/oai/spgw.conf
RUN sed -i 's/SGW_INTERFACE_NAME_FOR_S11              = "lo";/SGW_INTERFACE_NAME_FOR_S11              = "eth0";/g' /usr/local/etc/oai/spgw.conf
RUN sed -i 's/SGW_IPV4_ADDRESS_FOR_S11                = "127.0.11.2\/8";/SGW_IPV4_ADDRESS_FOR_S11                = "172.18.0.4\/16";/g' /usr/local/etc/oai/spgw.conf
RUN sed -i 's/SGW_IPV4_ADDRESS_FOR_S1U_S12_S4_UP      = "192.168.11.17\/24";/SGW_IPV4_ADDRESS_FOR_S1U_S12_S4_UP      = "172.18.0.4\/16";/g' /usr/local/etc/oai/spgw.conf

RUN apt-get install -y vim

RUN echo "#!/bin/bash" > sp.sh
RUN echo "/RECO/SCRIPTS/run_spgw &" > sp.sh
RUN echo "sleep 1" > sp.sh
RUN echo "ps -aux | grep spgw | grep -v grep | awk '{print $2}' | xargs kill" > sp.sh
RUN echo "/RECO/SCRIPTS/run_spgw" > sp.sh


CMD ["sh", "sp.sh"]
